FROM cfriedline/base:pineapp
MAINTAINER Chris Friedline <cfriedline@vcu.edu>
ENV PG_VERSION=9.4
run apt-get install -y postgresql-server-dev-$PG_VERSION build-essential postgresql-client-$PG_VERSION git
ENV PATH /usr/lib/postgresql/$PG_VERSION/bin:$PATH
volume /appdata
volume /dbdata
volume /anaconda
ENV PATH /anaconda/bin:$PATH
cmd bash