from ubuntu:15.04
maintainer Chris Friedline <cfriedline@vcu.edu>
user root
run mkdir /appdata
copy uwsgi.ini /appdata/
copy uwsgi_params /appdata/
copy requirements.txt /appdata/
copy nginx-app.conf /appdata/
copy supervisor-app.conf /appdata/
copy docker-entrypoint.sh /appdata/
volume /appdata
cmd /bin/bash 