FROM ubuntu:15.04
MAINTAINER Chris Friedline <cfriedline@vcu.edu>
RUN apt-get update 
RUN apt-get dist-upgrade -y
RUN apt-get install vim wget bzip2 -y
RUN groupadd docker
RUN useradd docker -m -g docker -s /bin/bash
USER docker
WORKDIR /home/docker
RUN wget https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda-2.2.0-Linux-x86_64.sh --no-check-certificate
RUN bash Anaconda-2.2.0-Linux-x86_64.sh -b -f
ENV PATH /home/docker/anaconda/bin:$PATH
RUN conda update conda
user root
