FROM cfriedline/base:latest
MAINTAINER Chris Friedline <cfriedline@vcu.edu>

#adapted from https://github.com/docker-library/postgres/blob/master/9.4/Dockerfile

USER root

# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
RUN groupadd -r postgres && useradd -m -s /bin/bash -r -g postgres postgres

RUN mkdir -p /etc/pki/tls/certs
RUN ln -s /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt

# grab gosu for easy step-down from root
RUN gpg --keyserver pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
RUN apt-get update 
RUN apt-get install -y curl
RUN curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/1.2/gosu-$(dpkg --print-architecture)"
RUN curl -o /usr/local/bin/gosu.asc -SL "https://github.com/tianon/gosu/releases/download/1.2/gosu-$(dpkg --print-architecture).asc" 
RUN gpg --verify /usr/local/bin/gosu.asc 
RUN rm /usr/local/bin/gosu.asc 
RUN chmod +x /usr/local/bin/gosu 

# make the "en_US.UTF-8" locale so postgres will be utf-8 enabled by default
RUN apt-get install -y locales \
	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

ENV PG_VERSION=9.4

RUN mkdir /docker-entrypoint-initdb.d

RUN apt-get install -y postgresql-common \
	&& sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf \
	&& apt-get install -y \
		postgresql-$PG_VERSION \
		postgresql-contrib-$PG_VERSION 

RUN mkdir -p /var/run/postgresql && chown -R postgres /var/run/postgresql

ENV PATH /usr/lib/postgresql/$PG_VERSION/bin:$PATH
ENV PGDATA /dbdata

RUN rm -rf /var/lib/apt/lists/*

COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh



volume /dbdata
volume /anaconda

ENV PATH /anaconda/bin:$PATH
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 5432
user root
CMD ["postgres"]