from debian:jessie
maintainer Chris Friedline <cfriedline@vcu.edu>
run mkdir /appdata
copy uwsgi.ini /appdata/
copy uwsgi_params /appdata/
copy requirements.txt /appdata/
copy nginx-app.conf /appdata/
copy supervisor-app.conf /appdata/
copy docker-entrypoint.sh /appdata/
volume /appdata
cmd bash