FROM cfriedline/base:pineapp
MAINTAINER Chris Friedline <cfriedline@vcu.edu>

#adapted from https://github.com/docker-library/postgres/blob/master/9.4/Dockerfile

USER root
ENV LANG en_US.utf8
ENV PG_VERSION=9.4

COPY docker-entrypoint.sh /

RUN groupadd -r postgres && \
useradd -m -s /bin/bash -r -g postgres postgres && \
echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
apt-get install readline-common && \
apt-get install locales && \
localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 && \
mkdir -p /etc/pki/tls/certs && \
ln -s /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt && \
gpg --keyserver pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 && \
apt-get install -y curl && \
curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/1.2/gosu-$(dpkg --print-architecture)" && \
curl -o /usr/local/bin/gosu.asc -SL "https://github.com/tianon/gosu/releases/download/1.2/gosu-$(dpkg --print-architecture).asc" && \
gpg --verify /usr/local/bin/gosu.asc && \
rm /usr/local/bin/gosu.asc && \
chmod +x /usr/local/bin/gosu && \
mkdir /docker-entrypoint-initdb.d && \
apt-get install -y postgresql-common && \
sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf && \
apt-get install -y postgresql-$PG_VERSION \
postgresql-contrib-$PG_VERSION \
postgresql-$PG_VERSION-postgis-2.1 && \
mkdir -p /var/run/postgresql && chown -R postgres /var/run/postgresql && \
rm -rf /var/lib/apt/lists/* && \
chmod +x /docker-entrypoint.sh

volume /dbdata
volume /anaconda

ENV PATH /anaconda/bin:$PATH
ENV PATH /usr/lib/postgresql/$PG_VERSION/bin:$PATH
ENV PGDATA /dbdata

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 5432
user root
CMD ["postgres"]