from cfriedline/base:pineapp
maintainer Chris Friedline <cfriedline@vcu.edu>
run apt-get install -y nginx supervisor postgresql-server-dev-9.4
# setup all the configfiles
volume /appdata
volume /anaconda
ENV PATH /anaconda/bin:$PATH
run echo "daemon off;" >> /etc/nginx/nginx.conf && \
rm /etc/nginx/sites-enabled/default && \
ln -s /appdata/nginx-app.conf /etc/nginx/sites-enabled/ && \
ln -s /appdata/supervisor-app.conf /etc/supervisor/conf.d/ && \
rm -rf /var/lib/apt/lists/*
expose 80
cmd ["supervisord", "-n"]


